package com.example.dynamodbdemo.customer.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@DynamoDBTable(tableName = "customer")
public class Customer {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String customerId;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email-index")
    private String email;

    @DynamoDBAttribute
    private Address address;

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "email-index")
    private String createdAt;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "lastName-index")
    private String lastNameIndex;

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getLastNameIndex() {
        return lastNameIndex;
    }

    public void setLastNameIndex(String lastNameIndex) {
        this.lastNameIndex = lastNameIndex;
    }

    // lastName이 변경될 때 인덱스 필드도 업데이트
    public void setLastName(String lastName) {
        this.lastName = lastName;
        this.lastNameIndex = lastName; // GSI용 필드 동기화
    }

    // Customer 생성 시 자동으로 현재 시간과 인덱스 필드 설정
    public void initializeFields() {
        if (this.createdAt == null) {
            this.createdAt = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        }
        if (this.lastName != null && this.lastNameIndex == null) {
            this.lastNameIndex = this.lastName;
        }
    }
}